import { StyleSheet } from "react-native";
import { PRIMARY, SECONDARY } from "../Style/Color";
export const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
    },
    coverImage: {
      top: 0,
      left: 0,
      right: 0,
      height: 400,
      resizeMode: 'cover',
      marginBottom: 20,
    },
    gradient: {
      position: 'absolute',
      top: 300,
      right: 0,
      bottom: 0,
      left: 0,
      justifyContent: 'flex-end',
    },
    overlayText: {
      color: 'white',
      fontSize: 20,
      fontFamily: 'Poppins-SemiBold',
      marginLeft: 30,
    },
    cardReview: {
      fontFamily: 'Poppins-Regular',
      fontSize: 16,
      color: 'white',
      marginLeft: 10,
    },
    review: {
      flexDirection: 'row',
      marginTop: 0,
      marginLeft: 30,
      marginBottom: 20,
    },
    backButton: {
      position: 'absolute',
      top: 30,
      left: 30,
      width: 44,
      height: 44,
      borderRadius: 50,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
    },
    overlay: {
      position: 'absolute',
      top: 30,
      left: 340,
      width: 44,
      height: 44,
      borderRadius: 50,
      backgroundColor: 'white',
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 5,
    },
    icon: {
      alignSelf: 'center',
    },
    features: {
      height: 45,
      width: 170,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: SECONDARY,
      justifyContent: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
    },
    featureList: {
      width: '87%',
      flexDirection: 'row',
      marginTop: 5,
      justifyContent: 'space-around',
    },
    featureText: {
      fontFamily: 'Poppins-Medium',
      fontSize: 14,
      color: PRIMARY,
      marginLeft: 10,
      marginTop: 4,
    },
    descriptionHeading: {
      fontFamily: 'Poppins-SemiBold',
      color: PRIMARY,
      fontSize: 22,
      marginBottom: 6,
    },
    description: {
      width: 330,
      marginTop: 20,
    },
    descriptionText: {
      fontFamily: 'Poppins-Regular',
      fontSize: 16,
      color: PRIMARY,
      marginTop: -10,
    },
    priceText: {
      fontFamily: 'Poppins-SemiBold',
      color: PRIMARY,
      fontSize: 18,
    },
  
    reviewText: {
      marginTop: -15,
      fontFamily: 'Poppins-Regular',
      fontSize: 14,
      color: PRIMARY,
    },
    addButton: {
      padding: 10,
      backgroundColor: '#007bff',
      borderRadius: 5,
    },
    addButtonText: {
      color: '#fff',
      fontSize: 16,
    },
    modalBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent background
    },
    modalContainer: {
      width: 360,
      height: 500,
      padding: 20,
      backgroundColor: '#fff',
      borderRadius: 10,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'center',
    },
    starContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 20,
    },
    input: {
      borderColor: '#ddd',
      borderWidth: 1,
      borderRadius: 5,
      padding: 10,
      height: 180,
      textAlignVertical: 'top',
      fontSize: 18,
      margin: 10,
    },
    titleInput: {
      borderColor: '#ddd',
      borderWidth: 1,
      borderRadius: 5,
      padding: 10,
      height: 50,
      textAlignVertical: 'top',
      fontSize: 18,
      margin: 10,
    },
    buttonContainer: {
      marginTop: 25,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    cancelButton: {
      color: PRIMARY,
      fontSize: 16,
      padding: 10,
      paddingRight: 20,
    },
  });